#!/bin/sh

#
# Implementation of CSmtp based on curl
#

print_syntax() {
  echo "Syntax: $(basename $0) -e <hostname> -u <username> -l <password> -s <sender-address> -r <recipient-address> [-r1 <second-recipient-address>] [-rsms <third-recipient-address>] -sub <subject> -msg <hex-encoded-message> [-tls] [-ssl] [-sp <port>] [-d] | [-h] | [-help]"
  return 0
}

[ "$1" ] || { print_syntax && return 0; }

# parse CSmtp command line arguments
eval set -- $(getopt -a -l sub:,msg:,sp:,tls,ssl,r1:,rsms:,help -o e:u:l:s:r:dh -- "$@")
while true; do
    case "$1" in
        -e)        host="$2"       ; shift 2 ;;
        -u)        username="$2"   ; shift 2 ;;
        -l)        password="$2"   ; shift 2 ;;
        -s)        sender="$2"     ; shift 2 ;;
        -r)        recipient="$2"  ; shift 2 ;;
        --r1)      recipient2="$2" ; shift 2 ;;
        --rsms)    recipient3="$2" ; shift 2 ;;
        -d)        debug=true      ; shift 1 ;;
        --sub)     subject="$2"    ; shift 2 ;;
        --msg)     hex_msg="$2"    ; shift 2 ;;
        --sp)      port="$2"       ; shift 2 ;;
        --tls)     security=tls    ; shift 1 ;;
        --ssl)     security=ssl    ; shift 1 ;;
        -h|--help) print_syntax    ; return 0;;
        --) shift ; break ;;
        *) echo "Unsupported argument: $1" ; return 1 ;;
    esac
done

# prepare curl arguments
date=$(date -R)
if [ -z "${security}" ]; then
  protocol="smtp"
  default_port=25
elif [ "${security}" = "tls" ]; then
  protocol="smtps"
  default_port=587
elif [ "${security}" = "ssl" ]; then
  protocol="smtps"
  default_port=465
fi
port="${port:-${default_port}}"
verbose="${debug:+-v}"
recipients="--mail-rcpt ${recipient}${recipient2:+ --mail-rcpt ${recipient2}}${recipient3:+ --mail-rcpt ${recipient3}}"

# send mail via curl
cat <<EOF | curl \
     ${security:+"--ssl-reqd"} \
     ${verbose} \
     --url "${protocol}://${host}:${port}" \
     --mail-from "${sender}" \
     ${recipients} \
     --user "${username}:${password}" \
     --upload-file -
From: SolarView <${sender}>
To: ${recipient}${recipient2:+,${recipient2}}${recipient3:+,${recipient3}}
Subject: ${subject}
Date: ${date}

$(echo -n "${hex_msg}" | sed 's/\([0-9A-F]\{2\}\)/\\\\\\x\1/gI' | xargs printf)
EOF
